### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by webmaster128** [konsumer/rawprotorust#3]
Right now `console_error_panic_hook` is used to convert Rust panics to console logs. This is a sane thing to do.

The alternative that could be done is avoid creating panics in Rust. Instead let the methods return `Resullt<SuccessType, ErrorType>`. This is supported by Wasm_bindgen in a way that the error case is transformed into a JavaScript exception. For simplicity `String` could be used as `ErrorType`.

The new API would look like this:

```rust
#[wasm_bindgen]
pub fn parse_raw(bytes: &[u8], js_path: &str, js_config: &JsValue) -> Result<JsValue, String> {


    // Return Ok(js_value) on success
    // and Err(error_string) on failure
}
```

**Comment by konsumer** [comment]
Yeh, I started with this, but couldn't get it to throw regular errors over wasm, maybe due to my noobness at rust. If you can make it work that seems fine, but I also I am totally fine with fast errors with nice stack/message (as `console_error_panic_hook` does.)

**Comment by konsumer** [comment]
Speaking of errors, I am seeing new errors introduced with the new merges:

<img width="422" alt="Screen Shot 2022-02-11 at 4 32 38 AM" src="https://user-images.githubusercontent.com/83857/153592074-c9201561-148d-4f23-ae44-6ea18c729754.png">

**Comment by konsumer** [comment]
I think it should return `Result<JsValue, JsValue>`, but I'm not sure.

**Comment by webmaster128** [comment]
_cannot parse integer from empty string_ happens when you use the query path ".1.", which happens in the middle of typing. Seems like the user input should be checked first before the rest of the processing is done.

**Comment by konsumer** [comment]
> cannot parse integer from empty string happens when you use the query path ".1.", which happens in the middle of typing.

Ah, ok. I don't remember seeing it before, but that makes sense.

> Seems like the user input should be checked first before the rest of the processing is done.

That, or a `catch`, or I am also fine with errors in the console on bad input (as it is.) It's non-fatal in JS, and it's nice to see the error, hiding in the console, if it's not working. Originally I had more input-checking, but I don't think it's really needed.

**Comment by konsumer** [comment]
Closing, but feel free to re-open, if you want to do errors differntly.
