### ISSUE TITLE
Simpler over-wasm format

### ISSUE THREAD

**Issue by konsumer** [konsumer/rawprotorust#4]
Since there are only 2 types (`Bytes`/`Int`) the type info that is passed over WASM-barrier is a bit redundant (type info is in the value, itself.)

I think this shape would be nicer to work with:

```js
[
  ['2.1.1.2.11.11.13.1.3', [2,1,1,2]],
  ['2.1.1.2.11.11.13.1.4', 0]
]
```

where each array element is an array-pair of string-path & value (which is either a number or array.)

I can convert into this in JS-space, but it might be nice if it was in rust-side, and be more genernally useful.

**Comment by webmaster128** [comment]
I wonder if we should preserve Fixed64/Fixed32/Varint at this level instead of pushing them all in one Int. This would allow for more type information on the display level.

The Int type currently holds a u128, which cannot be represented safely in JS numbers. So this would better be stored in a string.

Using lists of bytes is probably not great when working with JS. What about making them hex strings instead?

**Comment by konsumer** [comment]
I don't like hex for binary over just a plain array of bytes. `Buffer` is helpful for messing with byte-arrays in node, and browser/cloudflare-workers/deno have [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder), and all targets have polyfills for both. It's also simple to do `String.fromCharCode(...entry.value.Bytes)`, for example, which converts the whole array at once to string. Number-strings seem ok, but also byte-arrays could be used there too, and converted on the other side. I do like just having val/array to denote the 2 parent proto3 types (byte-array or number) but knowing the field is fixed gives us a bit more info, which might be nice to narrow down the possible types.

**Comment by webmaster128** [comment]
See https://github.com/confio/decode_raw/pull/4 for changes in the enum cases

**Comment by konsumer** [comment]
It looks really great. This would really help me at guessing, like knowing it's either 75 or a 0.<LOTS_OF_ZEROS>74 kind make it's clear what it probly is.

**Comment by webmaster128** [comment]
I started an integration in https://github.com/konsumer/rawprotorust/pull/5. Feel free to extend or discard as you see fit. I just wanted to make sure it works in general.

Cou can use the .bin files from https://github.com/confio/decode_raw/tree/main/docs for fixed64/fixed32 testing.

**Comment by konsumer** [comment]
Closing as this was merged. I think it might not be working with passing `config`, but I will open a new issue.
